0xPolygon/heimdall-v2

- x/bor/README.md
- x/chainmanager/README.md
- x/checkpoint/README.md
- x/clerk/README.md
- x/milestone/README.md
- x/stake/README.md
- x/topup/README.md
Please provide a detailed description of what was done in this PR
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag with a default value...)
> Updated the READMEs

- cmd/heimdalld/cmd/stake.go
- helper/tx.go
Please provide a detailed description of what was done in this PR
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag with a default value...)
> cmd: bug fix in stake and approve command

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- helper/config.go
- packaging/templates/package_scripts/postrm.profile
fix config related profiles and templates
> fix config related profiles and templates

- helper/call.go
- x/milestone/abci/abci.go
Batch calls instead of multiple gRPC requests. This provides more performance since replaces 10 multiple calls by a single one.
> get headers via batch rpc

- cmd/heimdalld/main.go
- version/version.go
Adds a `heimdalld_info` metric.
> feat: `heimdalld_info` metric

- .github/workflows/stale.yml
- cmd/heimdalld/cmd/root.go
- version/command.go
Fix the version command by avoiding checks on config files.
> fix version command

- builder/files/genesis-mainnet-v1.json
- builder/files/genesis-testnet-v4.json
- cmd/heimdalld/cmd/commands.go
- cmd/heimdalld/cmd/migrate.go
- cmd/heimdalld/cmd/testdata/dump-genesis.json
- cmd/heimdalld/cmd/testdata/migrated_dump-genesis.json
> SSF cherry pick lower blocktime

- app/abci.go
This PR addresses 2 issues in POS-2886:
- get block hash from keeper instead of execution layer
- remove retry logic from execution layer calls
There are two items in POS-2886 that are unaddressed. There is ongoing discussion with them and will be addressed if necessary in another PR.
> Abci cleanup

- app/abci.go
On first PrepareProposal the `ExecutionStateMetadata` will be missing so we should fetch latest block from the execution client.
> Fix initial payload build

- cmd/heimdalld/cmd/commands.go
Please provide a detailed description of what was done in this PR
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag with a default value...)
> increased precommit and prevote timeouts

- .github/workflows/ci.yml
- .github/workflows/govulncheck.yml
- .github/workflows/packager_deb.yml
- .github/workflows/release.yml
- .golangci.yml
- Makefile
- README.md
- go.mod
- Bump go version
- Migrate golanci-lint to v2
- fix e2e tests to continue when upload logs fails
> bump go version

- go.mod
- go.sum
> bump comet and cosmos

- app/abci.go
- x/bor/keeper/side_msg_server.go
- x/clerk/keeper/msg_server.go
- x/stake/keeper/msg_server.go
- x/stake/keeper/side_msg_server.go
- x/topup/keeper/side_msg_server.go
- x/topup/keeper/side_msg_server_test.go
Resolution for IF-FINDING-008.
Last point in the report skipped as it sounds risky.
> IF-FINDING-008

- bridge/processor/stake.go
- x/stake/keeper/msg_server.go
- x/stake/keeper/side_msg_server.go
- x/stake/keeper/validator.go
> IF-FINDIND-040

- x/stake/keeper/grpc_query.go
- x/stake/keeper/grpc_query_test.go
- x/stake/keeper/keeper_test.go
- x/stake/keeper/validator.go
> IF-FINDING-038

- x/stake/keeper/side_msg_server.go
- x/stake/keeper/side_msg_server_test.go
> IF-FINDING-035

- x/stake/keeper/validator.go
> IF-FINDING-031

- x/topup/keeper/msg_server.go
- x/topup/keeper/msg_server_test.go
> IF-FINDING-046

- x/milestone/keeper/grpc_query.go
- x/milestone/keeper/keeper.go
- x/milestone/keeper/keeper_test.go
> IF-FINDING-030

- helper/call.go
- x/milestone/abci/abci.go
- x/milestone/keeper/grpc_query.go
> IF-FINDING-028

- bridge/processor/checkpoint.go
> IF-FINDING-022

- x/checkpoint/keeper/grpc_query_test.go
- x/checkpoint/keeper/keeper_test.go
- x/checkpoint/keeper/msg_server.go
- x/checkpoint/keeper/msg_server_test.go
- x/checkpoint/types/msg.go
> IF-FINDING-019

- x/checkpoint/keeper/grpc_query.go
> IF-FINDING-016

- app/abci.go
- app/vote_ext_utils.go
- app/vote_ext_utils_test.go
Add milestone proposition validation to PrepareProposal and ProcessProposal
> IF-FINDING-027

- x/milestone/abci/abci.go
Improve milestone proposition validation
> IF-FINDING-026

- app/abci.go
Even if there are multiple checkpoints in a block, make sure we execute only the one from which the signatures were generated.
> IF-FINDING-017

- app/abci.go
- app/vote_ext_utils.go
Limit count of side tx responses per validator.
Limit size of non-rp vote extension per validator.
> IF-FINDING-010

- app/vote_ext_utils.go
Added `BlockHash` validation in `ValidateVoteExtensions`.
> IF-FINDING-011

- app/abci.go
Dont reject proposal on invalid nonrp vote extension
> Dont reject proposal on invalid nonrp vote extension

- migration/script/COMMANDS.md
- migration/script/README.md
- migration/script/RUNBOOK.md
- migration/script/migrate.sh
Script fixes and adjust docs accordingly
> adjust script and instructions

- bridge/listener/rootchain_selfheal.go
- bridge/listener/rootchain_selfheal_graph.go
Update logging messages for clarity, rename GraphQL entities from `stateSyncs` to `stateSynceds`, and adjust related struct/field names to match the new schema.
> chore: improve self-healing logging and GraphQL field names

- cmd/heimdalld/cmd/migrate.go
- helper/config.go
- migration/configs/heimdall-v1/heimdall-config.toml
- migration/configs/heimdall-v2/app.toml
- migration/script/COMMANDS.md
- migration/script/RUNBOOK.md
- migration/script/migrate.sh
Some changes for issues detected during mumbai migration.
> config fixes / script-docs update

- bridge/processor/span.go
Improve bridge span proposal logic logging
> Improve logging

- bridge/cmd/reset.go
- bridge/cmd/root.go
fixed `unsafe-reset-all` command
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it
(e.g., by adding a flag with a default value...)
> bridge: fixed unsafe-reset-all command

- app/abci.go
- x/milestone/abci/abci.go
Isolate the veblop logic to execute only post veblop.
> Isolate the veblop logic

- Makefile
> fix releaser

- cmd/heimdalld/cmd/ve_decode.go
- x/clerk/keeper/grpc_query.go
- x/clerk/keeper/grpc_query_test.go
This PR fixes the following:
- pagination on clerk's state syncs
- ve-decode command
> First release fixes

- packaging/deb/heimdalld/DEBIAN/prerm
Removing unnecessary stop in prerm
- [x ] Bugfix (non-breaking change that solves an issue)
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it
(e.g., by adding a flag with a default value...)
> Updating prerm

- helper/config.go
Ensure veblop isn't enabled by any means.
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it
(e.g., by adding a flag with a default value...)
> Disable veblop for all networks

- migration/containerized/1-MIGRATION-CHECKLIST.md
- migration/containerized/2-MIGRATION.md
- migration/systemd/1-MIGRATION-CHECKLIST.md
- migration/systemd/2b-MIGRATION-MANUAL.md
Update doc with migration timeline.
Remove optional `heimdallcli` command.
> update doc with migration timeline

- migration/containerized/1-MIGRATION-CHECKLIST.md
- migration/systemd/1-MIGRATION-CHECKLIST.md
Update erigon version in the checklist docs.
> update erigon version

- migration/containerized/2-MIGRATION.md
- migration/systemd/2a-MIGRATION-AUTOMATED.md
- migration/systemd/2b-MIGRATION-MANUAL.md
update docs with telemetry upgrade info
> update docs with telemetry upgrade info

- migration/containerized/1-MIGRATION-CHECKLIST.md
- migration/containerized/3-MIGRATION-ROLLBACK.md
- migration/systemd/1-MIGRATION-CHECKLIST.md
update instructions with open ports for sentries
> update instructions with open ports for sentries

- x/checkpoint/README.md
> update send-ack instruction

- x/clerk/keeper/grpc_query_test.go
Fixes TestGetRecordListWithTime_Pagination
> x/clerk: fix TestGetRecordListWithTime_Pagination

- x/clerk/keeper/grpc_query.go
- x/clerk/keeper/grpc_query_test.go
> Optimize state sync query

- go.mod
- go.sum
- x/clerk/keeper/grpc_query.go
- x/clerk/keeper/grpc_query_test.go
Update Comet version to `v0.2.1-polygon`.
> Bump comet version to v0.2.1-polygon

- bridge/listener/heimdall.go
- helper/util.go
start block for heimdall v2 listener
> start block for heimdall v2 listener

- common/cache/cache.go
- common/cache/cache_test.go
- x/checkpoint/keeper/side_msg_servers_test.go
- x/checkpoint/types/merkle.go
Cache the check if block exists and the root hash.
> Add cache for checkpoint validation

- x/bor/keeper/grpc_query.go
- x/checkpoint/keeper/grpc_query.go
- x/clerk/keeper/grpc_query.go
Please provide a detailed description of what was done in this PR
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it
(e.g., by adding a flag with a default value...)
> fix: remove offset limit

- .github/actions/kurtosis-post-run/action.yml
- .github/actions/kurtosis-pre-run/action.yml
- .github/configs/kurtosis-e2e.yml
- .github/configs/matic-cli-config.yml
- .github/workflows/ci.yml
- .github/workflows/kurtosis-e2e.yml
- integration-tests/kurtosis_smoke_test.sh
In future, we ideally want to replace matic-cli with kurtosis for E2E testing in CI, as matic-cli takes much time to set up and run smoke tests, while kurtosis is much more efficient.
> feat(ci): Kurtosis E2E tests

- bridge/listener/heimdall.go
HeimdallListener was using an internally created `client.Context` that does not inherit the `ChainID` set via CLI (`initRootCmd`).  
As a result, `cliCtx.ChainID` remains an empty string (`""`) when `fetchFromAndToBlock()` is called, causing `GetInitialBlockHeight()` to return `0`.  
This results in unnecessary polling from block 0 and repeated 2-minute `CommitTimeout` errors in `GetBeginBlockEvents()`, ultimately preventing checkpoint submission.
This PR resolves the issue by using `nodeStatus.NodeInfo.Network` as a fallback value when `cliCtx.ChainID` is not set.
N/A
This change is safe for all nodes. No flags or conditional logic added.
- Stopped local Heimdall node and removed bridge DB
- Ensured no `--chain-id` was passed via CLI
- Started node and verified fallback to …
> fix(listener): fallback to correct ChainID when cliCtx.ChainID is unset

- app/vote_ext_utils.go
- x/milestone/abci/abci.go
Dont error if validator not found
> Dont error if validator not found

- cmd/heimdalld/cmd/commands.go
- helper/config.go
- x/bor/keeper/side_msg_server.go
- x/bor/keeper/side_msg_server_test.go
PR to back merge `main` -> `develop`
> Back merge main->develop

- x/clerk/keeper/side_msg_server_test.go
This adds a UT in case the contract address in the clerk event from L1 and msg is not the same.
> Add test for wrong contract address in clerk event

- app/abci.go
- helper/config.go
- x/milestone/keeper/keeper.go
- x/milestone/keeper/keeper_test.go
Hotfix to delete faulty milestone for mainnet
> hotfix: milestone deletion

- .github/workflows/kurtosis-e2e.yml
> chore: bump kurtosis-pos
