- app/abci.go
- x/milestone/abci/abci.go
Allow pending proposition to overlap with previously settled milestone, therefore reducing the failure rate of pending milestones.
Benchmarked with 200ms (-+50ms) network latency. 
Before:
```
chain_milestone_whitelisteddelay {quantile="0.5"} 2.5496744665e+09
chain_milestone_whitelisteddelay {quantile="0.75"} 8.95483970175e+09
chain_milestone_whitelisteddelay {quantile="0.95"} 1.8309153385949997e+10
chain_milestone_whitelisteddelay {quantile="0.99"} 2.2199873968240017e+10
chain_milestone_whitelisteddelay {quantile="0.999"} 2.5827147059973003e+10
chain_milestone_whitelisteddelay {quantile="0.9999"} 2.5861035528e+10
```
After:
```
chain_milestone_whitelisteddelay {quantile="0.5"} 1.48279765e+09
chain_milestone_whitelisteddelay {quantile="0.75"} 1.9495698115e+09 …
```
> Refactor milestone proposition logic for deterministic consensus

- x/milestone/README.md
- x/milestone/keeper/keeper.go
- x/milestone/keeper/keeper_test.go
- x/milestone/types/events.go
This features enables us including milestone events on cosmos sdk event feature. It allows us subscribe to new blocks and filter milestone events.
You can query events via websocket endpoint:
```
echo '{ "jsonrpc": "2.0","method": "subscribe","id": 0,"params": {"query": "tm.event='"'NewBlock'"' AND milestone.number>0"} }' | websocat -n -t ws://127.0.0.1:26657/websocket
```
And the result will be like:
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"query": "tm.event='NewBlock'",
"data": {
"type": "tendermint/event/NewBlock",
"value": {
"block": {
"header": {
"version": {
"block": "11"
},
"chain_id": "heimdall-8509",
"height": "1983",
"time": "2025-03-04T15:13:39.613566597Z",
"last_block_id": {
"hash": "10AA8156D08D7B3EE963CDF8DC69AB4D2CEFD9151612120EEC6D23CC0AA58C08",
"parts": {
"total": 1, …
```
> Milestone Events

- cmd/heimdalld/cmd/migrate.go
- cmd/heimdalld/cmd/root.go
- helper/call.go
Fix the `migrate` command based on the migration execution needs:
1. Use absolute path for the `genesis` file path
2. Don't scan for configs in heimdall when running `migrate`
> fix migrate command

- .github/workflows/ci.yml
- cmd/heimdalld/cmd/migrate.go
- packaging/templates/config/priv_validator_state.json
In this PR we implement the following improvements:
1. Fix the `round` type in `priv_validator_state.json` template, since this is now an `int` while it used to be a `string` in `heimdall` v1.
2. Add a flag for the `migrate` command (set to `true` by default). This is helpful for testing purposes.
3. Install `solc-select` in the ci to make sure e2e-tests are working after the latest changes on genesis-contracts
> Fix round type / verify remote genesis hash with flag

- engine-api-poc/docker-compose.yaml
- engine-api-poc/grafana/provisioning/datasources/prometheus.yml
- engine-api-poc/prometheus/config.yml
- engine/auth.go
- engine/auth_test.go
- engine/client.go
- engine/metrics.go
- engine/types.go
This PR addresses https://polygon.atlassian.net/browse/POS-2890. 
- metrics interceptor to measure in/out bytes
- metrics that measure count and duration of rpcs calls in engine client
It integrates metrics into the engine client, with a prometheus metrics server.
Docker compose collects metrics with a prometheus server, and connects a grafana instance ( http://127.0.0.1:3000 ), allowing visualizations like this:
Metrics available are the standard `go_` metrics, and `heimdall_` 
Debugging:
- Start an erigon node 
- Configure an heimdall in engine mode to use the erigon EL, and start it 
- Go to http://127.0.0.1:2113 to see the metrics endpoint
Inspecting metrics:
- `docker compose up erigon-0 node0 prometheus graphana`
- navigate to …
> metrics for engine client

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- .github/workflows/packager_deb.yml
- cmd/heimdalld/cmd/migration/verify/verify.go
Update the packager to fix the bug in pre-release workflow (as done in v1).
Also fix the `countJSONArrayEntries` to assume 0 entries if an array doesn't exist (e.g. no state-syncs)
> Update packager and fix jsonObjectsCount

- Dockerfile
By first calling `go mod download` with just `go.mod` and `go.sum` copied, if no changes were found on `go.mod` it Docker caches this step. In general, the download step takes around 200s whiles the build itself take less than 40s.
> go mod dowload step cached on dockerfile

- app/abci.go
Add comments to better clarify code for IF-FINDING-009
When applied the recommendation, I got consensus failure on initial block with ve enabled, if I remove that second check
```
May 12 15:23:56 mardizzone-009-bor-1 heimdalld[40031]: 3:23PM INF finalizing commit of block hash=5C7A4F155C168A3414EA373B3B4C0619E9E1A89DD00AD539671C421006DA339B height=1 module=consensus num_txs=1 root=E3B0C44298FC1C149AFBF4>
May 12 15:23:56 mardizzone-009-bor-1 heimdalld[40031]: 3:23PM ERR CONSENSUS FAILURE!!! err="runtime error: slice bounds out of range [1:0]" module=consensus stack="goroutine 258 [running]:\nruntime/debug.Stack()\n\t/home/ubunt>
May 12 15:23:56 mardizzone-009-bor-1 heimdalld[40031]: 3:23PM INF service stop impl=baseWAL module=consensus msg="Stopping baseWAL service" …
```
> IF-FINDING-009

- x/bor/keeper/keeper.go
If last seed producer not found, return nil value
> If last seed producer not found, return nil value

- app/app.go
This PR sets the default heimdall config path to `/var/lib/heimdall`.
> Fix default heimdall config path

- cmd/heimdalld/cmd/commands.go
- cmd/heimdalld/cmd/root.go
This PR dedups initalization of `initClientCtx` that results in creation of default heimdall home dir (`/var/lib/heimdall`) while running `init` despite providing a custom home path.
> Dedup init of client context

- x/bor/keeper/msg_server.go
Use bor last used span instead of heimdall last span for spans backfill validation.
> Use bor last used span instead of heimdall last span

- cmd/heimdalld/cmd/commands.go
This PR bumps the timeout for the REST server to become operational during the node startup to 1 hour. This is generally to prevent the node from crashing, especially observed when heimdall-v2 was started just after migration in amoy. We can later reduce it once nodes are migrated and the network is in stable condition.
> cmd: increase rpc server timeout during startup to 1 hour

- cmd/heimdalld/cmd/root.go
- version/command.go
Fixes #322 
Also:
- Missing JSON Support. Code had JSON logic but no --output flag.
- JSON Only Worked for --long.
Output:
```bash
build/heimdalld version -o json
{
"version": "0.2.5-12-ge608d8cc"
}
```
```bash
build/heimdalld version --long --output json       
{
"name": "heimdall",
"server_name": "heimdalld",
"client_name": "heimdalld",
"version": "0.2.5-13-g5b9da490",
"commit": "5b9da490316c3dd2eae1fd6dcc0c69720dcee2fa",
"go": "go version go1.24.4 darwin/arm64"
}
```
> fix(cmd): ignore IAVL log output and version command

- x/bor/keeper/grpc_query.go
- x/checkpoint/keeper/grpc_query.go
- x/clerk/keeper/grpc_query.go
Adds a check for offset to prevent requests than can have large offsets and can potentially use large amounts of time and memory.
> chore: add max offset check to prevent large offset reqs

- Dockerfile
- go.mod
Switched to Go 1.24‑alpine & Alpine 3.22; adopted a two‑stage build with SSH+cache mounts for go mod download and make build, then copied only the heimdalld binary and sh entrypoint into a minimal Alpine runtime (just certs, no Bash)—trimming the final image from hundreds of megabytes down to mere megabytes.
> Dockerfile: use multi-stage build optimisation

- Dockerfile.release
Bump alpine image to use `alpine:latest` in `Dockerfile.release`.
> chore: bump alpine image in release dockerfile

- cmd/heimdalld/cmd/commands.go
This PR fixes the `import-validator-key` command by properly registering the crypto types prior to importing.
> Fix import-validator-key command

- app/abci.go
- app/app.go
- app/vote_ext_utils.go
- metrics/abci.go
- metrics/api/bor.go
- metrics/api/checkpoint.go
- metrics/api/clerk.go
- metrics/api/common.go
- metrics/api/stake.go
- metrics/api/topup.go
- metrics/consensus/consensus.go
- metrics/metrics.go
- metrics/version.go
- x/bor/keeper/side_msg_server.go
- x/checkpoint/keeper/side_msg_server.go
- x/clerk/keeper/side_msg_server.go
- x/stake/keeper/side_msg_server.go
- x/topup/keeper/side_msg_server.go
This PR extends the metrics for side and post-transaction handlers for each module. Also adds a `countervec` for approved, rejected, and failure to reach a 2/3rd agreement for side txs.
Also, it adds summaryvec for abci handlers.
> chore: side msg and abci handler metrics

- cmd/heimdalld/cmd/commands.go
- helper/config.go
- x/bor/keeper/side_msg_server.go
- x/bor/keeper/side_msg_server_test.go
This PR adds a check to verify the proposed span length. Also cherry-picks the fix for  `generate-keystore` command.
> Add span range check

- helper/config.go
This PR sets `tallyFixHeight`, `disableVPCheckHeight` and `disableValSetCheckHeight` for amoy network.
> Set voting power and valset check heights for amoy

- app/abci_test.go
- x/milestone/abci/abci.go
Query blocks for milestone up to latest bor block, instead of max miestone length to reduce load on bor
> Query blocks for milestone up to latest bor block

- cmd/heimdalld/cmd/root.go
- cmd/heimdalld/cmd/sanitize.go
- helper/config.go
- helper/sanitize.go
- packaging/templates/config/amoy/app.toml
- packaging/templates/config/amoy/config.toml
- packaging/templates/config/mainnet/app.toml
- packaging/templates/config/mainnet/config.toml
Including new default prune and compaction flags to be inserted on Heimdall. These new configurations comes from the new introduced CometBFT features: https://github.com/0xPolygon/cometbft/pull/23 and https://github.com/0xPolygon/cometbft/pull/24
> Default Prune and Compaction Config

- README.md
- cmd/heimdalld/cmd/commands.go
- Remove `cat` from priv files docs in README, to let the operator decide how to fetch the string. 
- Add heimdalld command to generate node id from comet
> update readme and commands
